### ISSUE TITLE
Miniworld Player Reference Does Not Appear in the Device View on the Monitor

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#158]
**Using EVR-staging[0.0.5], 4/21/17 [#150]**

Not a huge issue, but one to note:

When referencing a screen-cap of my monitor's device view, I noticed that the Miniworld player reference does not appear in the device view on the monitor.

_Although this _was occurring on the monitor view, there were no issues when viewing in the HMD.__  

![ezgif com-optimize 3](https://cloud.githubusercontent.com/assets/25187040/25291986/1c56a464-2689-11e7-9b03-121fa55051aa.gif)

(Still able to see controllers, but not the Player Head)

Again, not a big issue that would affect a user's workflow, but would be a useful fix for the purpose of screen-caps and demos.

**Comment by amirebrahimi** [comment]
So, this is by-design currently when using the presentation camera. If you turn off the presentation camera it shows, but that's only because the left eye texture from the HMD is being copied and used for the view shown on the monitor. For the presentation camera, we are farther back from the player and are looking down, so that we can see the hands moving. If we rendered the HMD objects it would get in the way, so they are hidden from rendering. MiniWorld happens to respect the same rendering, hence why they don't show up.
