### ISSUE TITLE
Remove fast/slow translation/rotation thresholds for joystick movement

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#198]
Particularly rotation. Simply unusable. Can we switch to new Vive version? Say hold down joystick to enter locomotion mode, then hold down trigger and point to move?

**Comment by amirebrahimi** [comment]
We had fast/slow thresholds to potentially reduce motion sickness by switching over to faster speeds when near the max joystick/touchpad input to avoid acceleration. However, this was hard to intuit from a user's perspective because the threshold was not disclosed. Now, there is a non-linear curve for translation/rotation, but it is directly controlled by the user, so doesn't seem to induce motion sickness.

The max translation and rotation speeds were reduced as well.
