### ISSUE TITLE
Hide EditorVR GameObjects in the hierarchy

### ISSUE THREAD

**Issue by leith-bartrich** [Unity-Technologies/EditorVR#60]
The attached video illustrates a way to break EditorVR easily, as a user, by deleting the Input Manager.

But I think it illustrates the peril in using fairly unprotected scene objects as the editor itself.

While it's probably trivial to filter the object I used to illustrate, from the VR Hierarchy workspace, it is not filtered from the main Unity UI or 3rd party systems and tools.  I'd think there should be some thought put into how to protect this class of object in a more comprehensive manner.

https://www.youtube.com/watch?v=AehOh1Db4dY

**Comment by mtschoen-unity** [comment]
Yes. We intend to set HideFlags on the EditorVR hierarchy and any other objects that EVR creates.

The InputManager will eventually be replaced by core features.

**Comment by leith-bartrich** [comment]
Is it safe to say that such object creation should be routed through the U class in the Utility package?

**Comment by amirebrahimi** [comment]
@leith-bartrich, realized that no one responded to your previous question. U was renamed to separate Utils classes, so the one you are talking about is ObjectUtils. Currently, this is an internal class, so for object creation that must "run in edit mode" we'll need to provide an interface for that. Otherwise, you can Instantiate as you normally would if it is an object that should live in the user's scene even after saving.
