### ISSUE TITLE
Menu content not loading

### ISSUE THREAD

**Issue by upscalebaby** [Unity-Technologies/EditorVR#69]
Firstly there's no Unity icon on the Vive controllers but opening the menu still works - but there's no content loaded into the menus. I can spin the menu around but nothing loads in it so I can't do anything except teleport around atm. Using SteamVR 1.2.

**Comment by amirebrahimi** [comment]
What graphics card do you have?

**Comment by upscalebaby** [comment]
970gtx 376.53 driver, I reckon I could've updated the driver but I didn't think of it.

**Comment by amirebrahimi** [comment]
Hmm..Was going to ask you if you saw any errors on the console. Unfortunately, we've never seen this on our end cross any of our machines.

**Comment by mtschoen-unity** [comment]
This actually sounds like an issue with the DLL for the UI system. I have had issues with projects targeting the wrong DLL in the past. What happens if you go to Create -> UI -> Button in the EditorVR version of Unity?

If you're still stuck, and don't mind taking a somewhat-extreme approach, uninstall all versions of Unity on your computer, install just the EditorVR build, and try creating a clean project.

**Comment by amirebrahimi** [comment]
@upscalebaby - It's possible that your UI layer is just turned off. Seemed to fix this person's problem: https://forum.unity3d.com/threads/no-user-interface-on-touch-controllers.446471/#post-2985226

**Comment by upscalebaby** [comment]
@amirebrahimi thanks alot! I reinstalled a clean version with new drivers but it still did not work, when I checked the layers the UI layer was indeed turned off! (strange since it was a fresh install and new scene). Finally I'll get to try it out!
